### ISSUE TITLE
extensions.conf - wait time after modem playback

### ISSUE THREAD

**Issue by jamesjcarter** [beardyjay/warvox-asterisk#1]
Hi,  

Should the wait(10) be wait(100) after modem sound playback?

   ...
   exten => 3,1,Wait(0.25)
   exten => 3,n,Answer()
   exten => 3,n,Playback(modem)
   exten => 3,n,Wait(10)         《---- 100 ?
   ...

-James

**Comment by beardyjay** [comment]
I had to check this one as I haven't used this project in a while. I think it should be 10 and the rest of the `Waits` should also be `Wait(10)` instead of `Wait(100)`.

I would have to check it out tho and see what happens, have you tried it yet?  

https://wiki.asterisk.org/wiki/display/AST/Application_Wait

**Comment by beardyjay** [comment]
Okay so I just cloned this to a new EC2 instance and `Wait(10)` is correct. 

The other extension options are `Wait(100)` as they call [Playtones()](https://wiki.asterisk.org/wiki/display/AST/Application_PlayTones) and execution continues to the next line so that's why the `Wait(100)` is needed,

The modem wav sound uses [Playback()](https://wiki.asterisk.org/wiki/display/AST/Application_Playback) which does not continue execution so `Wait(10)` is fine. 

If anything the `Playback(fax)` on line 51 can be changed to `Wait(10)` but I think by the time Warvox reaches its timeout then it's either hanged up or has already identified it as a Fax/Modem. 

Hope this helps.

**Comment by jamesjcarter** [comment]
Thanks for the reply.

Innovative piece of work, nice one :)

I noticed it a while ago but only just got round to asking about it.  I do
recall I had some issue but now can't remember if it was related or fixed
coincidentally  with another change I made.

I'll fire up the VMWARE I'm using for warvox and report back if I have a
problem.


Regards,
jc

**Comment by beardyjay** [comment]
Brilliant thanks! :)
